### ISSUE TITLE
Homepage updates

### ISSUE THREAD

**Issue by chiefmonky** [PlebeianTech/plebeian-market#11]
Centre the big main steps
Delete Step 1

1. Tweet with Photos
2. Click Start
3. Collect Sats

================

Add a large line of text below the Steps (above) and above the "Enter the Market" button 

Use the same animated typewriter CSS stying as on the homepage of https://hackmd.io/ 

The text should read:

Sell anything... <insert variations>... and get paid in sats 

The <variations> are:

1 hour of your time 
bitcoin art
your furniture 
an ASIC miner
Baklava
your next book

Use pure CSS like the example below or something you feel is better... but no javascript:

https://codepen.io/thiagoteles/pen/ogoxLw

================
<img width="1872" alt="Screenshot 2022-05-31 at 14 31 16" src="https://user-images.githubusercontent.com/55535154/172666658-f29922e7-64c1-4ff2-9c47-a2a9b2455bcd.png">

**Comment by 151henry151** [comment]
Is something about like [this](https://www.loom.com/share/c5e2af58120140cf92b27d4653808f77) the right idea?
I think it might actually look a little better if step 1 was just "Tweet Photos" so that it would look like
![Screenshot at 2022-06-09 03-15-22](https://user-images.githubusercontent.com/6581719/172787804-5ab72a05-bd31-4dc2-85f2-611ccb028c5a.png)

**Comment by chiefmonky** [comment]
Yes agreed... but the items "time, art, etc" are what flashes like a typewriter in the middle right? 

btw your avatar looks fresh... have you changed your hair?

**Comment by ibz** [comment]
Yes, I think the items should be flashing in the correct spot, not underneath. Like on hackmd's website...

**Comment by 151henry151** [comment]
@chiefmonky does [this](https://www.loom.com/share/99c01e7088dc44cc9c664f07bf5f53af) look about right? I still need to work on it to make it look good on mobile, but for the desktop version is this the right idea?
