### ISSUE TITLE
Bugs on homepage

### ISSUE THREAD

**Issue by rolznz** [PlebeianTech/plebeian-market#299]
The images sometimes do not match the item (e.g. The item said "Buddha" but the picture was of a hat), and the top items continuously change.

**Comment by ktecho** [comment]
That problem has already been solved at `master`, and will be fixed in the homepage when we deploy the `Nostr version`. That will happen "Very Soon (TM)".

**Comment by ibz** [comment]
Wasn't "very soon" but it happened after all. New version is live. Old bugs should be gone. New bugs probably added.
