### ISSUE TITLE
edit resume button doesn't do anything

### ISSUE THREAD

**Issue by ralyodio** [PlebeianTech/plebeian-market#348]

**Comment by miguepollo** [comment]
yes @ralyodio  the screen is this 

![image](https://github.com/PlebeianTech/plebeian-market/assets/127879645/1d6cff2c-31b5-48ac-b066-c6db2df2d66f)

**Comment by ktecho** [comment]
Hi @ralyodio 

You're right, that screen has some problems... Anyways, we'll launch the Nostr-based version of Plebeian Market soon. This first version won't have the Skills Market enabled, but it will be improved and enabled at a later stage.

Thanks for reporting the problem!
